### ISSUE TITLE
Make live tracking (`makersinit`) easier to install

### ISSUE THREAD

**Issue by sjmog** [makersacademy/git_receiver#4]
```
As a student
So I can easily be tracked
I want to install makersinit stably and easily
```

A gem or clickable app would make sense. It should also ping the Git Receiver to check it's working.

**Comment by sjmog** [comment]
At the moment this is a copy-pasted script into a `.bash_profile`

But it needs the following features:
- 1-click install of `makersinit`
- A ping to a verification server that verifies `makersinit` is correctly installed

**Comment by sjmog** [comment]
Should be done by beginning of week starting Feb 1st.

**Comment by sjmog** [comment]
We are implementing this as a Gem.

**Comment by sjmog** [comment]
See https://github.com/makersacademy/makers

**Comment by sjmog** [comment]
Please see https://github.com/makersacademy/makersinit for this gem.

**Comment by ptolemybarnes** [comment]
Looks good @sjmog. Do you need a squirrel on this?

**Comment by silvabox** [comment]
@samm: in this code:

``` ruby
  def self.initialize_pre_push_script
    File.open(script_path) do |f|
      f.read
    end
    copy_script_to_hook
    remove_sample_hook
  end
```

What does the first `File.open` do?

**Comment by sjmog** [comment]
It reads the file contents to the IO stream? Which is then copied using `IO.copy_stream(script_path, "#{GIT_HOOKS_PATH}/pre-push")`. I thought you had to open and read the stream to use `copy_stream`.

**Comment by sjmog** [comment]
Released!
